# Generated by Django 5.0.3 on 2024-03-18 03:02

import django.core.validators
import django.db.models.deletion
import django_cpf_cnpj.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='NOME COMPLETO:')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14, verbose_name='CADASTRO DE PESSOA FÍSICA (CPF):')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=20, verbose_name='GÊNERO:')),
                ('data_nascimento', models.DateField(verbose_name='DATA DE NASCIMENTO:')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('graduacao', 'Pós-Graduação')], max_length=50, verbose_name='ESCOLARIDADE:')),
                ('area_atuacao', models.CharField(choices=[('artesanato', 'Artesanato'), ('agricultura', 'Agricultura Urbana'), ('comercio', 'Comércio'), ('estetica', 'Estética e Beleza'), ('gastronomia', 'Gastronomia'), ('industria', 'Indústria'), ('servico', 'Serviço')], max_length=50, verbose_name='ATIVIDADE QUE ATUA OU DESEJA ATUAR:')),
                ('endereco', models.CharField(max_length=100, verbose_name='ENDEREÇO RESIDENCIAL:')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPLEMENTO:')),
                ('bairro', models.CharField(max_length=100, verbose_name='BAIRRO:')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='O formato do CEP deve ser "XXXXX-XXX".', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP:')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name=' UF:')),
                ('contato', models.CharField(max_length=20, verbose_name='CONTATO:')),
                ('email', models.EmailField(max_length=254, verbose_name='E-MAIL:')),
                ('interesse_ter_negocio', models.CharField(choices=[('s', 'SIM'), ('n', 'NÃO')], max_length=1, verbose_name='O INTERESSADO TEM INTERESSE EM POSSUIR UM NEGÓCIO?')),
                ('preferencia_aula', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=20, verbose_name='VOCÊ PREFERE ASSISTIR AULAS ONLINE OU PRESENCIAIS?')),
                ('meio_comunicacao_aula', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20, verbose_name='VOCÊ GOSTARIA QUE ENVIÁSSEMOS O LINK PARA AS AULAS POR?')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME FANTASIA')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ:')),
                ('situacao_empresa', models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('n_ativa', 'Não Ativa')], max_length=50, null=True, verbose_name='SITUAÇÃO DA EMPRESA:')),
                ('porte_empresa', models.CharField(blank=True, choices=[('MEI', 'Microempreendedor individual (MEI)'), ('ME', 'Microempresa (ME)')], max_length=50, null=True, verbose_name='PORTE:')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='DATA ABERTURA:')),
                ('cnae_principal', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O formato do CNAE deve ser "XXXX-X/XX".', regex='^\\d{4}-\\d{1}/\\d{2}$')], verbose_name='CNAE PRINCIPAL (Classificação Nacional de Atividades  Econômicas):')),
                ('setor', models.CharField(blank=True, choices=[('comercio', 'Comércio'), ('servico', 'Serviço'), ('agronegocios', 'Agronegócios'), ('industria', 'Indústria')], max_length=50, null=True, verbose_name='SETOR:')),
                ('tipo_vinculo', models.CharField(blank=True, choices=[('representante', 'Representante'), ('responsavel', 'Responsável')], max_length=50, null=True, verbose_name='TIPO DE VÍNCULO')),
                ('assistir_casa', models.CharField(choices=[('s', 'SIM'), ('n', 'NÃO')], max_length=1, verbose_name='TEM CONDIÇÕES DE ASSISTIR AULAS ONLINE?')),
                ('if_true_assistir_casa', models.CharField(choices=[('computador', 'Computador'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('outro', 'Outro')], max_length=10, verbose_name='SE VOCÊ RESPONDEU “SIM” À PERGUNTA ANTERIOR, POR ONDE VOCÊ ASSISTIRIA ÀS AULAS ONLINE?')),
                ('modulo_marketing', models.BooleanField(default=False, verbose_name='Marketing (Como dominar o mercado digital)')),
                ('modulo_financeiro', models.BooleanField(default=False, verbose_name='Financeiro (Domine o fluxo de caixa de sua empresa)')),
                ('modulo_planejamento', models.BooleanField(default=False, verbose_name='Planejamento (Modelo de negócio que funciona, aprenda a fazer o seu)')),
                ('outros', models.BooleanField(default=False, verbose_name='Outros')),
                ('responsabilizacao', models.BooleanField(default=False, verbose_name='Declaro estar CIENTE de que sou plenamente responsável pela veracidade das informações aqui prestadas, vez que serão comprovadas no início da capacitação, e de que a falsidade das informações acima implicará sanções cabíveis de natureza civil, administrativa e criminal.')),
                ('manejo_dados', models.BooleanField(default=False, verbose_name='Declaro estar CIENTE de que, em razão da parceria com o SEBRAE, a responsabilidade pelo manejo dos dados supra solicitados é compartilhada entre o SEBRAE e a Coordenadoria de Empreendedorismo e Sustentabilidade de Negócios (COESNE), na Secretaria Municipal do Desenvolvimento Econômico (SDE), caso seja verificada a necessidade de alterações.')),
                ('armazenamento_dados', models.BooleanField(default=False, verbose_name='DECLARO estar CIENTE quanto ao armazenamento dos meus dados no banco de cadastro da COESNE e pelo SEBRAE, para a formulação futura de políticas públicas com foco em públicos específicos, e para que EU seja informado(a) sobre a execução de novos projetos pela COESNE, respeitada a confidencialidade dos dados, que somente serão tratados por colaboradores formalmente autorizados no âmbito da SDE.')),
                ('autoriazacao', models.BooleanField(default=False, verbose_name='AUTORIZO ao SEBRAE o armazenamento e a utilização dos meus dados com a finalidade de oferecer produtos e serviços do seu interesse, realizar pesquisas relacionadas ao seu atendimento, realizar comunicações oficiais pelo SEBRAE ou por nossos prestadores de serviços por meio de diversos canais de comunicação e enriquecer o seu cadastro a partir de base de dados controladas pelo SEBRAE.')),
                ('comunicacao', models.CharField(choices=[('s', 'Sim, eu concordo.'), ('n', 'Nao, eu nao concordo.')], max_length=1, verbose_name='Voce autoriza que as comunicações sejam realizadas por meio de ligação, mensagem instantânea e e-mail?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
