# Generated by Django 5.0.3 on 2024-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='assistir_casa',
            new_name='assistir_online',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='autoriazacao',
            new_name='autorizacao',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='outros',
            new_name='modulo_outros',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='escolaridade',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('graduacao', 'Graduação'), ('pos_graduacao', 'Pós-Graduação')], max_length=50, verbose_name='ESCOLARIDADE:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='if_true_assistir_casa',
            field=models.CharField(blank=True, choices=[('computador', 'Computador'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('outro', 'Outro')], max_length=10, null=True, verbose_name='SE VOCÊ RESPONDEU “SIM” À PERGUNTA ANTERIOR, POR ONDE VOCÊ ASSISTIRIA ÀS AULAS ONLINE?'),
        ),
    ]
