# Generated by Django 5.0.3 on 2024-03-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0002_rename_assistir_casa_ficha_assistir_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='comunicacao',
            field=models.CharField(choices=[('s', 'Sim, eu concordo.'), ('n', 'Não, eu não concordo.')], max_length=1, verbose_name='Você autoriza que as comunicações sejam realizadas por meio de ligação, mensagem instantânea e e-mail?'),
        ),
    ]
