# Generated by Django 5.0.3 on 2024-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0004_alter_ficha_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CNAE PRINCIPAL (Classificação Nacional de Atividades  Econômicas):'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CADASTRO DE PESSOA FÍSICA (CPF):'),
        ),
    ]
