services:
  db-dev:
    image: postgres
    volumes:
      - ./data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ceac
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: z_xs-!@*wyq6&ewf38rtjl#!5-obs*8mtdrpov%zq_91w6
      POSTGRES_ROOT_PASSWORD: 2vb&voihgu*9+0m#6(tyzkkm+vi=_s!_d-^osug5*2a%2o(+5)
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - net-dev
    restart: unless-stopped

  adminer-dev:
    image: adminer
    ports:
      - 8080:8080 
    networks:
      - net-dev
    restart: unless-stopped

networks:
  net-dev:
    driver: bridge
