version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    env_file:
      - ./backend/.env
    ports:
      - 8080:${ADMINER_EXPOSE_PORT}
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge
