version: '3.8'

services:
  gunicorn:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend/staticfiles:/staticfiles
    entrypoint: bash entrypoint.sh
    expose:
      - 8000
    networks:
      - net
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    build: ./backend/nginx
    volumes:
      - ./backend/staticfiles:/staticfiles
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    depends_on:
      - gunicorn
    restart: unless-stopped

  db:
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
      - /data/sgceac:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:${ADMINER_EXPOSE_PORT}
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
  staticfiles:
