version: '3.8'

services:
  gunicorn:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend/staticfiles:/staticfiles
    entrypoint: bash entrypoint.sh
    expose:
      - 8000
    ports:
      - 8001:8000
    networks:
      - net
    depends_on:
      - db
    # stdin_open: true
    # tty: true
    restart: unless-stopped

  nginx:
    build: ./backend/nginx
    volumes:
      - ./backend/staticfiles:/staticfiles
    # expose:
    #   - 80
    ports:
      - 80:80
    networks:
      - net
    depends_on:
      - gunicorn
    restart: unless-stopped

  db:
    image: mysql
    env_file:
      - ./backend/.env
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
  staticfiles:
