version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - /data/sgceac_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sgceac
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: z_xs-!@*wyq6&ewf38rtjl#!5-obs*8mtdrpov%zq_91w6
      POSTGRES_ROOT_PASSWORD: 2vb&voihgu*9+0m#6(tyzkkm+vi=_s!_d-^osug5*2a%2o(+5)
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080 
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge
