version: '3.8'

services:
  # app:
  #   build: ./backend
  #   image: sgceac
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   entrypoint: bash
  #   command: start.sh
  #   expose:
  #     - 8000
  #   ports:
  #     - 80:8000
  #   networks:
  #     - net
  #   depends_on:
  #     - db
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped

  db:
    image: mysql
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
    driver: bridge