version: '3.8'

services:
  gunicorn:
    build: .
    env_file:
      - ./.env
    working_dir: /app
    volumes:
      - static:/static
    entrypoint: bash entrypoint.sh
    expose:
      - 8000
    networks:
      - net
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    depends_on:
      - gunicorn
    restart: unless-stopped

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - /data/ceac_backend:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - net
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
  static:
