# Generated by Django 5.0.3 on 2024-11-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_permissaoextra_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': [('searchUser', 'Buscar Usuário'), ('createUser', 'Criar Usuário'), ('searchPerfil', 'Buscar Perfil'), ('createPerfil', 'Criar Perfil')]},
        ),
    ]
