# Generated by Django 5.0.3 on 2025-02-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': [('searchUser', 'Buscar Usuário'), ('createUser', 'Criar Usuário'), ('searchPerfil', 'Buscar Perfil'), ('createPerfil', 'Criar Perfil')]},
        ),
    ]
