# Generated by Django 5.0.3 on 2025-02-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': [('manageOperator', 'Gerenciar Operadores'), ('createOperator', 'Criar Operador'), ('managePerfil', 'Gerenciar Perfis'), ('createPerfil', 'Criar Perfil')]},
        ),
    ]
