# Generated by Django 5.0.3 on 2024-03-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0003_remove_ficha_usuario_alter_ficha_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CADASTRO DE PESSOA FÍSICA (CPF):'),
        ),
    ]
