# Generated by Django 5.0.3 on 2024-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0005_alter_ficha_cep_alter_ficha_cnae_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='contato',
            field=models.CharField(max_length=11, verbose_name='CONTATO:'),
        ),
    ]
