# Generated by Django 5.0.3 on 2024-05-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0006_alter_ficha_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100, verbose_name='ATIVIDADES DISPONÍVEIS:')),
                ('disponivel', models.BooleanField(default=True, verbose_name='ESSA ATIVIDADE ESTÁ DIPONÍVEL:')),
            ],
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='area_atuacao',
        ),
        migrations.AddField(
            model_name='ficha',
            name='atividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='capacita.atividade', verbose_name='ATIVIDADE QUE ATUA OU DESEJA ATUAR:'),
            preserve_default=False,
        ),
    ]
