# Generated by Django 5.0.3 on 2024-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0007_atividade_remove_ficha_area_atuacao_ficha_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='ESSA ATIVIDADE ESTÁ DIPONÍVEL'),
        ),
    ]
