# Generated by Django 5.0.3 on 2024-07-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0008_alter_atividade_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('capacita_buscarFicha', 'Capacita/Buscar Ficha')]},
        ),
    ]
