# Generated by Django 5.0.3 on 2024-07-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0009_alter_ficha_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('capacita_buscarFicha', 'Capacita/Buscar Ficha'), ('capacita_criarFicha', 'Capacita/Criar Ficha')]},
        ),
    ]
