# Generated by Django 5.0.3 on 2024-07-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0010_alter_ficha_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('capacita_buscarCliente', 'Capacita/Buscar Cliente'), ('capacita_criarCliente', 'Capacita/Criar Cliente')]},
        ),
    ]
