# Generated by Django 5.0.3 on 2024-07-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0011_alter_ficha_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ficha',
            new_name='Cliente',
        ),
    ]
