# Generated by Django 5.0.3 on 2024-08-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0012_rename_ficha_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Ficha',
        ),
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('capacita_buscarFicha', 'Capacita/Buscar Ficha'), ('capacita_criarFicha', 'Capacita/Criar Ficha')]},
        ),
    ]
