# Generated by Django 5.0.3 on 2024-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0013_rename_cliente_ficha_alter_ficha_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='ESSA ATIVIDADE ESTÁ DISPONÍVEL'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='armazenamento_dados',
            field=models.BooleanField(default=False, verbose_name='DECLARO ESTAR CIENTE QUANTO AO ARMAZENAMENTO DOS MEUS DADOS NO BANCO DE CADASTRO DA COESNE E PELO SEBRAE, PARA A FORMULAÇÃO FUTURA DE POLÍTICAS PÚBLICAS COM FOCO EM PÚBLICOS ESPECÍFICOS, E PARA QUE EU SEJA INFORMADO(A) SOBRE A EXECUÇÃO DE NOVOS PROJETOS PELA COESNE, RESPEITADA A CONFIDENCIALIDADE DOS DADOS, QUE SOMENTE SERÃO TRATADOS POR COLABORADORES FORMALMENTE AUTORIZADOS NO ÂMBITO DA SDE.'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assistir_online',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, verbose_name='TEM CONDIÇÕES DE ASSISTIR AULAS ONLINE?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='autorizacao',
            field=models.BooleanField(default=False, verbose_name='AUTORIZO AO SEBRAE O ARMAZENAMENTO E A UTILIZAÇÃO DOS MEUS DADOS COM A FINALIDADE DE OFERECER PRODUTOS E SERVIÇOS DO SEU INTERESSE, REALIZAR PESQUISAS RELACIONADAS AO SEU ATENDIMENTO, REALIZAR COMUNICAÇÕES OFICIAIS PELO SEBRAE OU POR NOSSOS PRESTADORES DE SERVIÇOS POR MEIO DE DIVERSOS CANAIS DE COMUNICAÇÃO E ENRIQUECER O SEU CADASTRO A PARTIR DE BASE DE DADOS CONTROLADAS PELO SEBRAE.'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CNAE PRINCIPAL (CLASSIFICAÇÃO NACIONAL DE ATIVIDADES ECONÔMICAS):'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='comunicacao',
            field=models.CharField(choices=[('S', 'SIM, EU CONCORDO.'), ('N', 'NÃO, EU NÃO CONCORDO.')], max_length=1, verbose_name='VOCÊ AUTORIZA QUE AS COMUNICAÇÕES SEJAM REALIZADAS POR MEIO DE LIGAÇÃO, MENSAGEM INSTANTÂNEA E E-MAIL?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DATA DE CRIAÇÃO DA FICHA'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='escolaridade',
            field=models.CharField(choices=[('FUNDAMENTAL', 'ENSINO FUNDAMENTAL'), ('MEDIO', 'ENSINO MÉDIO'), ('GRADUACAO', 'GRADUAÇÃO'), ('POS_GRADUACAO', 'PÓS-GRADUAÇÃO')], max_length=50, verbose_name='ESCOLARIDADE:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=20, verbose_name='GÊNERO:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='if_true_assistir_casa',
            field=models.CharField(blank=True, choices=[('COMPUTADOR', 'COMPUTADOR'), ('CELULAR', 'CELULAR'), ('TABLET', 'TABLET'), ('OUTRO', 'OUTRO')], max_length=10, null=True, verbose_name='SE VOCÊ RESPONDEU “SIM” À PERGUNTA ANTERIOR, POR ONDE VOCÊ ASSISTIRIA ÀS AULAS ONLINE?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='interesse_ter_negocio',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1, verbose_name='O INTERESSADO TEM INTERESSE EM POSSUIR UM NEGÓCIO?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='manejo_dados',
            field=models.BooleanField(default=False, verbose_name='DECLARO ESTAR CIENTE DE QUE, EM RAZÃO DA PARCERIA COM O SEBRAE, A RESPONSABILIDADE PELO MANEJO DOS DADOS SUPRA SOLICITADOS É COMPARTILHADA ENTRE O SEBRAE E A COORDENADORIA DE EMPREENDEDORISMO E SUSTENTABILIDADE DE NEGÓCIOS (COESNE), NA SECRETARIA MUNICIPAL DO DESENVOLVIMENTO ECONÔMICO (SDE), CASO SEJA VERIFICADA A NECESSIDADE DE ALTERAÇÕES.'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='meio_comunicacao_aula',
            field=models.CharField(choices=[('WHATSAPP', 'WHATSAPP'), ('EMAIL', 'EMAIL')], max_length=20, verbose_name='VOCÊ GOSTARIA QUE ENVIÁSSEMOS O LINK PARA AS AULAS POR?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='modulo_financeiro',
            field=models.BooleanField(default=False, verbose_name='FINANCEIRO (DOMINE O FLUXO DE CAIXA DE SUA EMPRESA)'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='modulo_marketing',
            field=models.BooleanField(default=False, verbose_name='MARKETING (COMO DOMINAR O MERCADO DIGITAL)'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='modulo_outros',
            field=models.BooleanField(default=False, verbose_name='OUTROS'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='modulo_planejamento',
            field=models.BooleanField(default=False, verbose_name='PLANEJAMENTO (MODELO DE NEGÓCIO QUE FUNCIONA, APRENDA A FAZER O SEU)'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='porte_empresa',
            field=models.CharField(blank=True, choices=[('MEI', 'MICROEMPREENDEDOR INDIVIDUAL (MEI)'), ('ME', 'MICROEMPRESA (ME)')], max_length=50, null=True, verbose_name='PORTE:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='preferencia_aula',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('PRESENCIAL', 'PRESENCIAL')], max_length=20, verbose_name='VOCÊ PREFERE ASSISTIR AULAS ONLINE OU PRESENCIAIS?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='responsabilizacao',
            field=models.BooleanField(default=False, verbose_name='DECLARO ESTAR CIENTE DE QUE SOU PLENAMENTE RESPONSÁVEL PELA VERACIDADE DAS INFORMAÇÕES AQUI PRESTADAS, VEZ QUE SERÃO COMPROVADAS NO INÍCIO DA CAPACITAÇÃO, E DE QUE A FALSIDADE DAS INFORMAÇÕES ACIMA IMPLICARÁ SANÇÕES CABÍVEIS DE NATUREZA CIVIL, ADMINISTRATIVA E CRIMINAL.'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='setor',
            field=models.CharField(blank=True, choices=[('COMERCIO', 'COMÉRCIO'), ('SERVICO', 'SERVIÇO'), ('AGRONEGOCIOS', 'AGRONEGÓCIOS'), ('INDUSTRIA', 'INDÚSTRIA')], max_length=50, null=True, verbose_name='SETOR:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='situacao_empresa',
            field=models.CharField(blank=True, choices=[('ATIVA', 'ATIVA'), ('N_ATIVA', 'NÃO ATIVA')], max_length=50, null=True, verbose_name='SITUAÇÃO DA EMPRESA:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('REPRESENTANTE', 'REPRESENTANTE'), ('RESPONSAVEL', 'RESPONSÁVEL')], max_length=50, null=True, verbose_name='TIPO DE VÍNCULO'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='uf',
            field=models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2, verbose_name='UF:'),
        ),
    ]
