# Generated by Django 5.0.3 on 2024-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0014_alter_atividade_disponivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='contato',
        ),
        migrations.AddField(
            model_name='ficha',
            name='celular',
            field=models.CharField(default=1, max_length=11, verbose_name='CELULAR:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='fixo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='FIXO:'),
        ),
    ]
