# Generated by Django 5.0.3 on 2024-08-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0015_remove_ficha_contato_ficha_celular_ficha_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='nis',
            field=models.CharField(default=0, max_length=11, verbose_name='NIS (Número de Identificação Social)'),
            preserve_default=False,
        ),
    ]
