# Generated by Django 5.0.3 on 2024-08-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0016_ficha_nis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='nis',
        ),
    ]
