# Generated by Django 5.0.3 on 2024-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0017_remove_ficha_nis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='if_true_assistir_casa',
            field=models.CharField(choices=[('COMPUTADOR', 'COMPUTADOR'), ('CELULAR', 'CELULAR'), ('TABLET', 'TABLET'), ('OUTRO', 'OUTRO')], default=0, max_length=10, verbose_name='SE VOCÊ RESPONDEU “SIM” À PERGUNTA ANTERIOR, POR ONDE VOCÊ ASSISTIRIA ÀS AULAS ONLINE?'),
            preserve_default=False,
        ),
    ]
