# Generated by Django 5.0.3 on 2024-08-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0018_alter_ficha_if_true_assistir_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='if_true_assistir_casa',
            field=models.CharField(blank=True, choices=[('COMPUTADOR', 'COMPUTADOR'), ('CELULAR', 'CELULAR'), ('TABLET', 'TABLET'), ('OUTRO', 'OUTRO')], max_length=10, null=True, verbose_name='SE VOCÊ RESPONDEU “SIM” À PERGUNTA ANTERIOR, POR ONDE VOCÊ ASSISTIRIA ÀS AULAS ONLINE?'),
        ),
    ]
