# Generated by Django 5.0.3 on 2024-08-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0019_alter_ficha_if_true_assistir_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulosAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Módulo')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Seleção')),
            ],
        ),
        migrations.AlterField(
            model_name='ficha',
            name='atividade',
            field=models.CharField(max_length=100, verbose_name='ATIVIDADE QUE ATUA OU DESEJA ATUAR:'),
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='armazenamento_dados',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='autorizacao',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='comunicacao',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='manejo_dados',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='modulo_financeiro',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='modulo_marketing',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='modulo_outros',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='modulo_planejamento',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='responsabilizacao',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CADASTRO DE PESSOA FÍSICA (CPF):'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-MAIL:'),
        ),
        migrations.CreateModel(
            name='FichaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.ficha')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.modulosaprendizagem')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='modulos_aprendizagem',
            field=models.ManyToManyField(blank=True, through='capacita.FichaModulo', to='capacita.modulosaprendizagem', verbose_name='MÓDULOS DE CAPACITAÇÃO'),
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
