# Generated by Django 5.0.3 on 2024-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0020_modulosaprendizagem_alter_ficha_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulosaprendizagem',
            name='descricao',
            field=models.TextField(default=1, unique=True, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assistir_online',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='TEM CONDIÇÕES DE ASSISTIR AULAS ONLINE?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='atividade',
            field=models.CharField(choices=[('ARTESANATO', 'ARTESANATO'), ('AGRICULTURA URBANA', 'AGRICULTURA_URBANA'), ('COMÉRCIO', 'COMERCIO'), ('ESTÉTICA E BELEZA', 'ESTETICA_E_BELEZA'), ('GASTRONOMIA', 'GASTRONOMIA'), ('INDÚSTRIA', 'INDUSTRIA'), ('SERVIÇO', 'SERVICO')], verbose_name='ATIVIDADE QUE ATUA OU DESEJA ATUAR:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='bairro',
            field=models.CharField(verbose_name='BAIRRO:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='complemento',
            field=models.CharField(blank=True, null=True, verbose_name='COMPLEMENTO:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='endereco',
            field=models.CharField(verbose_name='ENDEREÇO RESIDENCIAL:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='escolaridade',
            field=models.CharField(choices=[('FUNDAMENTAL', 'ENSINO FUNDAMENTAL'), ('MEDIO', 'ENSINO MÉDIO'), ('GRADUACAO', 'GRADUAÇÃO'), ('POS_GRADUACAO', 'PÓS-GRADUAÇÃO')], verbose_name='ESCOLARIDADE:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], verbose_name='GÊNERO:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='if_true_assistir_casa',
            field=models.CharField(blank=True, choices=[('COMPUTADOR', 'COMPUTADOR'), ('CELULAR', 'CELULAR'), ('TABLET', 'TABLET'), ('OUTRO', 'OUTRO')], null=True, verbose_name='SE VOCÊ RESPONDEU “SIM” À PERGUNTA ANTERIOR, POR ONDE VOCÊ ASSISTIRIA ÀS AULAS ONLINE?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='interesse_ter_negocio',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], verbose_name='O INTERESSADO TEM INTERESSE EM POSSUIR UM NEGÓCIO?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='meio_comunicacao_aula',
            field=models.CharField(choices=[('WHATSAPP', 'WHATSAPP'), ('EMAIL', 'EMAIL')], verbose_name='VOCÊ GOSTARIA QUE ENVIÁSSEMOS O LINK PARA AS AULAS POR?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nome_completo',
            field=models.CharField(verbose_name='NOME COMPLETO:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nome_fantasia',
            field=models.CharField(blank=True, null=True, verbose_name='NOME FANTASIA'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='porte_empresa',
            field=models.CharField(blank=True, choices=[('MEI', 'MICROEMPREENDEDOR INDIVIDUAL (MEI)'), ('ME', 'MICROEMPRESA (ME)')], null=True, verbose_name='PORTE:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='preferencia_aula',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('PRESENCIAL', 'PRESENCIAL')], verbose_name='VOCÊ PREFERE ASSISTIR AULAS ONLINE OU PRESENCIAIS?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='setor',
            field=models.CharField(blank=True, choices=[('COMERCIO', 'COMÉRCIO'), ('SERVICO', 'SERVIÇO'), ('AGRONEGOCIOS', 'AGRONEGÓCIOS'), ('INDUSTRIA', 'INDÚSTRIA')], null=True, verbose_name='SETOR:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='situacao_empresa',
            field=models.CharField(blank=True, choices=[('ATIVA', 'ATIVA'), ('N_ATIVA', 'NÃO ATIVA')], null=True, verbose_name='SITUAÇÃO DA EMPRESA:'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('REPRESENTANTE', 'REPRESENTANTE'), ('RESPONSAVEL', 'RESPONSÁVEL')], null=True, verbose_name='TIPO DE VÍNCULO'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='uf',
            field=models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='modulosaprendizagem',
            name='nome',
            field=models.CharField(unique=True, verbose_name='Nome do Módulo'),
        ),
    ]
