# Generated by Django 5.0.3 on 2024-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0021_modulosaprendizagem_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulosaprendizagem',
            name='descricao',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Descrição'),
        ),
    ]
