# Generated by Django 5.0.3 on 2024-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0022_alter_modulosaprendizagem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='atividade',
            field=models.CharField(choices=[('ARTESANATO', 'ARTESANATO'), ('AGRICULTURA_URBANA', 'AGRICULTURA URBANA'), ('COMERCIO', 'COMÉRCIO'), ('ESTETICA_E_BELEZA', 'ESTÉTICA E BELEZA'), ('GASTRONOMIA', 'GASTRONOMIA'), ('INDUSTRIA', 'INDÚSTRIA'), ('SERVICO', 'SERVIÇO')], verbose_name='ATIVIDADE QUE ATUA OU DESEJA ATUAR:'),
        ),
    ]
