# Generated by Django 5.0.3 on 2024-08-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0023_alter_ficha_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='modulos_aprendizagem',
        ),
        migrations.DeleteModel(
            name='FichaModulo',
        ),
        migrations.AddField(
            model_name='ficha',
            name='modulos_aprendizagem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='capacita.modulosaprendizagem', verbose_name='MÓDULOS DE CAPACITAÇÃO'),
            preserve_default=False,
        ),
    ]
