# Generated by Django 5.0.3 on 2024-08-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0024_remove_ficha_modulos_aprendizagem_delete_fichamodulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('buscarFicha', 'Buscar Ficha'), ('criarFicha', 'Criar Ficha')]},
        ),
    ]
