# Generated by Django 5.0.3 on 2024-08-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0025_alter_ficha_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='modulos_aprendizagem',
            new_name='modulo_aprendizagem',
        ),
    ]
