# Generated by Django 5.0.3 on 2024-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0026_rename_modulos_aprendizagem_ficha_modulo_aprendizagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModulosAprendizagem',
            new_name='ModulosCapacita',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='modulo_aprendizagem',
            new_name='modulo_capacita',
        ),
    ]
