# Generated by Django 5.0.3 on 2024-11-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0029_alter_ficha_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('searchFicha', 'Buscar Ficha'), ('createFicha', 'Criar Ficha')]},
        ),
    ]
