# Generated by Django 5.0.3 on 2025-01-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0030_alter_ficha_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('searchFicha', 'Buscar Ficha'), ('createFicha', 'Criar Ficha'), ('editFicha', 'Editar Ficha'), ('deleteFicha', 'Deletar Ficha')]},
        ),
    ]
