# Generated by Django 5.0.3 on 2025-02-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0033_alter_ficha_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'permissions': [('manageFicha', 'Gerenciar Fichas'), ('createFicha', 'Criar Ficha')]},
        ),
    ]
